<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;
use Illuminate\Support\Str;

class InventorySeeder extends Seeder
{
    public function run(): void
    {
        // Create departments first
        $departments = [
            ['name' => 'Office', 'code' => 'OFF', 'status' => 'active'],
            ['name' => 'Laboratory', 'code' => 'LAB', 'status' => 'active'], 
            ['name' => 'Classroom', 'code' => 'CLS', 'status' => 'active'],
            ['name' => 'Maintenance', 'code' => 'MNT', 'status' => 'active'],
            ['name' => 'Computer Engineering', 'code' => '', 'status' => 'active'],
            ['name' => 'Criminal Justice', 'code' => 'CCJ', 'status' => 'active'],
            ['name' => 'Medicine', 'code' => 'MED', 'status' => 'active'],
            ['name' => 'Engineering', 'code' => 'ENG', 'status' => 'active'],
            ['name' => 'Architecture', 'code' => 'ARC', 'status' => 'active'],
            ['name' => 'Mathematics', 'code' => 'MTH', 'status' => 'active'],
            ['name' => 'Business', 'code' => 'BUS', 'status' => 'active'],
            ['name' => 'Information Technology', 'code' => 'IT', 'status' => 'active']
        ];

        DB::table('departments')->insert($departments);

        // Then create items
        $items = [
            [
                'name' => 'Industrial Floor Mop',
                'description' => 'Heavy-duty commercial grade floor mop with microfiber head',
                'category' => 'cleaning',
                'department' => 'maintenance',
                'current_quantity' => 15,
                'minimum_quantity' => 5,
                'maximum_quantity' => 20,
                'status' => 'available',
                'usage_frequency' => 'daily',
                'budget_category' => 'regular',
                'sku' => 'MOP' . Str::random(5),
                'unit_price' => 25.99,
                'unit_type' => 'piece',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Wireless Projector',
                'description' => 'HD projector with wireless connectivity',
                'category' => 'electronics',
                'department' => 'classroom',
                'current_quantity' => 3,
                'minimum_quantity' => 5,
                'maximum_quantity' => 10,
                'status' => 'low_stock',
                'usage_frequency' => 'daily',
                'budget_category' => 'department',
                'sku' => 'PRJ' . Str::random(5),
                'unit_price' => 599.99,
                'unit_type' => 'piece',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Laboratory Microscope',
                'description' => 'Digital microscope with 1000x magnification',
                'category' => 'equipment',
                'department' => 'laboratory',
                'current_quantity' => 4,
                'minimum_quantity' => 8,
                'maximum_quantity' => 15,
                'status' => 'low_stock',
                'usage_frequency' => 'daily',
                'budget_category' => 'department',
                'sku' => 'MIC' . Str::random(5),
                'unit_price' => 1299.99,
                'unit_type' => 'piece',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Whiteboard Markers',
                'description' => 'Pack of 12 assorted color markers',
                'category' => 'supplies',
                'department' => 'classroom',
                'current_quantity' => 25,
                'minimum_quantity' => 20,
                'maximum_quantity' => 100,
                'status' => 'available',
                'usage_frequency' => 'weekly',
                'budget_category' => 'regular',
                'sku' => 'MRK' . Str::random(5),
                'unit_price' => 12.99,
                'unit_type' => 'pack',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'First Aid Kit',
                'description' => 'Complete emergency medical supplies kit',
                'category' => 'safety',
                'department' => 'office',
                'current_quantity' => 8,
                'minimum_quantity' => 5,
                'maximum_quantity' => 15,
                'status' => 'available',
                'usage_frequency' => 'monthly',
                'budget_category' => 'emergency',
                'sku' => 'FAK' . Str::random(5),
                'unit_price' => 45.99,
                'unit_type' => 'kit',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Office Desk Chair',
                'description' => 'Ergonomic adjustable office chair',
                'category' => 'furniture',
                'department' => 'office',
                'current_quantity' => 12,
                'minimum_quantity' => 10,
                'maximum_quantity' => 30,
                'status' => 'available',
                'usage_frequency' => 'daily',
                'budget_category' => 'department',
                'sku' => 'CHR' . Str::random(5),
                'unit_price' => 199.99,
                'unit_type' => 'piece',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lab Safety Goggles',
                'description' => 'Chemical splash resistant safety goggles',
                'category' => 'safety',
                'department' => 'laboratory',
                'current_quantity' => 30,
                'minimum_quantity' => 20,
                'maximum_quantity' => 50,
                'status' => 'available',
                'usage_frequency' => 'daily',
                'budget_category' => 'regular',
                'sku' => 'GOG' . Str::random(5),
                'unit_price' => 15.99,
                'unit_type' => 'piece',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Document Scanner',
                'description' => 'High-speed automatic document scanner',
                'category' => 'electronics',
                'department' => 'office',
                'current_quantity' => 2,
                'minimum_quantity' => 1,
                'maximum_quantity' => 5,
                'status' => 'available',
                'usage_frequency' => 'daily',
                'budget_category' => 'department',
                'sku' => 'SCN' . Str::random(5),
                'unit_price' => 399.99,
                'unit_type' => 'piece',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Paper Towels',
                'description' => 'Industrial roll paper towels',
                'category' => 'cleaning',
                'department' => 'maintenance',
                'current_quantity' => 40,
                'minimum_quantity' => 30,
                'maximum_quantity' => 100,
                'status' => 'available',
                'usage_frequency' => 'daily',
                'budget_category' => 'regular',
                'sku' => 'PTW' . Str::random(5),
                'unit_price' => 8.99,
                'unit_type' => 'roll',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Interactive Whiteboard',
                'description' => 'Digital interactive whiteboard with touch capability',
                'category' => 'electronics',
                'department' => 'classroom',
                'current_quantity' => 2,
                'minimum_quantity' => 2,
                'maximum_quantity' => 8,
                'status' => 'available',
                'usage_frequency' => 'daily',
                'budget_category' => 'department',
                'sku' => 'IWB' . Str::random(5),
                'unit_price' => 1499.99,
                'unit_type' => 'piece',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lab Coat',
                'description' => 'White laboratory coat with pockets',
                'category' => 'safety',
                'department' => 'laboratory',
                'current_quantity' => 25,
                'minimum_quantity' => 15,
                'maximum_quantity' => 40,
                'status' => 'available',
                'usage_frequency' => 'daily',
                'budget_category' => 'regular',
                'sku' => 'LCT' . Str::random(5),
                'unit_price' => 35.99,
                'unit_type' => 'piece',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Filing Cabinet',
                'description' => '4-drawer metal filing cabinet',
                'category' => 'furniture',
                'department' => 'office',
                'current_quantity' => 5,
                'minimum_quantity' => 3,
                'maximum_quantity' => 10,
                'status' => 'available',
                'usage_frequency' => 'daily',
                'budget_category' => 'department',
                'sku' => 'CAB' . Str::random(5),
                'unit_price' => 249.99,
                'unit_type' => 'piece',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Student Desk',
                'description' => 'Adjustable height student desk with storage',
                'category' => 'furniture',
                'department' => 'classroom',
                'current_quantity' => 30,
                'minimum_quantity' => 25,
                'maximum_quantity' => 50,
                'status' => 'available',
                'usage_frequency' => 'daily',
                'budget_category' => 'department',
                'sku' => 'DSK' . Str::random(5),
                'unit_price' => 159.99,
                'unit_type' => 'piece',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Chemical Storage Cabinet',
                'description' => 'Fire-resistant chemical storage cabinet',
                'category' => 'safety',
                'department' => 'laboratory',
                'current_quantity' => 3,
                'minimum_quantity' => 2,
                'maximum_quantity' => 6,
                'status' => 'available',
                'usage_frequency' => 'daily',
                'budget_category' => 'department',
                'sku' => 'CSC' . Str::random(5),
                'unit_price' => 899.99,
                'unit_type' => 'piece',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Vacuum Cleaner',
                'description' => 'Industrial grade vacuum cleaner',
                'category' => 'cleaning',
                'department' => 'maintenance',
                'current_quantity' => 4,
                'minimum_quantity' => 3,
                'maximum_quantity' => 8,
                'status' => 'available',
                'usage_frequency' => 'daily',
                'budget_category' => 'regular',
                'sku' => 'VAC' . Str::random(5),
                'unit_price' => 349.99,
                'unit_type' => 'piece',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ];

        // Insert items
        foreach ($items as $item) {
            DB::table('items')->insert($item);
        }
    }
}